version: "3.3"

services:
  db:
      image: postgres:14.0
      restart: always
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          PGDATA: /var/lib/postgresql/data
      volumes:
          - db-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"
volumes:
  db-data: